<?php

	echo '<form>';
	$domains = $beget->getDomians();
	
	echo 'домен: <select name="domain">';
		foreach($domains as $item){
			if(is_array($item)){
				foreach($item["result"] as $result){
					echo '<option value="'.$result["fqdn"].'">'.$result["fqdn"].'</option>';
				}
			}
		}
	echo '</select>';
	
	echo 'кол-во поддоменов: <input type="number" value="0" name="count">: BEGET<br>';
	echo '<input type="checkbox" name="dns" value="1" checked>Привязать DNS к CLOUD ';
	echo '<input type="radio" id="" name="ADD_DCFKKT" value="1" checked>Добавить домен в CLOUD, KLO, KEITARO';
	echo '<input type="radio" id="" name="ADD_DCFKKT" value="0">Домен уже Добавлен<br>';
	echo 'KLOAK: ';
	echo '<input name="black" type="text" class="form-control" placeholder="ссылка на черный">';
	echo '<input name="white" type="text" class="form-control" placeholder="ссылка на белый">';

	echo '<select name="type" class="form-control">';
	echo '<option value="ANY">любой трафик</option>';
	echo '<option value="MOB">моб трафик</option>';
	echo '<option value="DESC">десктоп трафик</option>';
	echo '</select>';
											echo '<select name="geo" class="form-control">';
                                                echo '<option value="AF">Afghanistan</option>';
                                                echo '<option value="AX">Åland Islands</option>';
                                                echo '<option value="AL">Albania</option>';
                                                echo '<option value="DZ">Algeria</option>';
                                                echo '<option value="AS">American Samoa</option>';
                                                echo '<option value="AD">Andorra</option>';
                                                echo '<option value="AO">Angola</option>';
                                                echo '<option value="AI">Anguilla</option>';
                                                echo '<option value="AQ">Antarctica</option>';
                                                echo '<option value="AG">Antigua and Barbuda</option>';
                                                echo '<option value="AR">Argentina</option>';
                                                echo '<option value="AM">Armenia</option>';
                                                echo '<option value="AW">Aruba</option>';
                                                echo '<option value="AU">Australia</option>';
                                                echo '<option value="AT">Austria</option>';
                                                echo '<option value="AZ">Azerbaijan</option>';
                                                echo '<option value="BS">Bahamas</option>';
                                                echo '<option value="BH">Bahrain</option>';
                                                echo '<option value="BD">Bangladesh</option>';
                                                echo '<option value="BB">Barbados</option>';
                                                echo '<option value="BY">Belarus</option>';
                                                echo '<option value="BE">Belgium</option>';
                                                echo '<option value="BZ">Belize</option>';
                                                echo '<option value="BJ">Benin</option>';
                                                echo '<option value="BM">Bermuda</option>';
                                                echo '<option value="BT">Bhutan</option>';
                                                echo '<option value="BO">Bolivia</option>';
                                                echo '<option value="BA">Bosnia and Herzegovina</option>';
                                                echo '<option value="BW">Botswana</option>';
                                                echo '<option value="BV">Bouvet Island</option>';
                                                echo '<option value="BR">Brazil</option>';
                                                echo '<option value="IO">British Indian Ocean Territory</option>';
                                                echo '<option value="VG">British Virgin Islands</option>';
                                                echo '<option value="BN">Brunei Darussalam</option>';
                                                echo '<option value="BG">Bulgaria</option>';
                                                echo '<option value="BF">Burkina Faso</option>';
                                                echo '<option value="BI">Burundi</option>';
                                                echo '<option value="KH">Cambodia</option>';
                                                echo '<option value="CM">Cameroon</option>';
                                                echo '<option value="CA">Canada</option>';
                                                echo '<option value="CV">Cape Verde</option>';
                                                echo '<option value="KY">Cayman Islands</option>';
                                                echo '<option value="CF">Central African</option>';
                                                echo '<option value="TD">Chad</option>';
                                                echo '<option value="CL">Chile</option>';
                                                echo '<option value="CN">China</option>';
                                                echo '<option value="CX">Christmas Island</option>';
                                                echo '<option value="CC">Cocos (Keeling) Islands</option>';
                                                echo '<option value="CO">Colombia</option>';
                                                echo '<option value="KM">Comoros</option>';
                                                echo '<option value="CK">Cook Islands</option>';
                                                echo '<option value="CR">Costa Rica</option>';
                                                echo '<option value="CI">Côte dIvoire</option>';
                                                echo '<option value="HR">Croatia</option>';
                                                echo '<option value="CU">Cuba</option>';
                                                echo '<option value="CY">Cyprus</option>';
                                                echo '<option value="CZ">Czech Republic</option>';
                                                echo '<option value="KP">Democratic People"s Republic of Korea</option>';
                                                echo '<option value="DK">Denmark</option>';
                                                echo '<option value="DJ">Djibouti</option>';
                                                echo '<option value="DM">Dominica</option>';
                                                echo '<option value="DO">Dominican Republic</option>';
                                                echo '<option value="EC">Ecuador</option>';
                                                echo '<option value="EG">Egypt</option>';
                                                echo '<option value="SV">El Salvador</option>';
                                                echo '<option value="GQ">Equatorial Guinea</option>';
                                                echo '<option value="ER">Eritrea</option>';
                                                echo '<option value="EE">Estonia</option>';
                                                echo '<option value="ET">Ethiopia</option>';
                                                echo '<option value="FK">Falkland Islands</option>';
                                                echo '<option value="FO">Faroe Islands</option>';
                                                echo '<option value="FM">Federated States of Micronesia</option>';
                                                echo '<option value="FJ">Fiji</option>';
                                                echo '<option value="FI">Finland</option>';
                                                echo '<option value="FR">France</option>';
                                                echo '<option value="GF">French Guiana</option>';
                                                echo '<option value="PF">French Polynesia</option>';
                                                echo '<option value="TF">French Southern Territories</option>';
                                                echo '<option value="GA">Gabon</option>';
                                                echo '<option value="GM">Gambia</option>';
                                                echo '<option value="GE">Georgia</option>';
                                                echo '<option value="DE">Germany</option>';
                                                echo '<option value="GH">Ghana</option>';
                                                echo '<option value="GI">Gibraltar</option>';
                                                echo '<option value="GR">Greece</option>';
                                                echo '<option value="GL">Greenland</option>';
                                                echo '<option value="GD">Grenada</option>';
                                                echo '<option value="GP">Guadeloupe</option>';
                                                echo '<option value="GU">Guam</option>';
                                                echo '<option value="GT">Guatemala</option>';
                                                echo '<option value="GN">Guinea</option>';
                                                echo '<option value="GW">Guinea-Bissau</option>';
                                                echo '<option value="GY">Guyana</option>';
                                                echo '<option value="HT">Haiti</option>';
                                                echo '<option value="HM">Heard Island and McDonald Islands</option>';
                                                echo '<option value="HN">Honduras</option>';
                                                echo '<option value="HK">Hong Kong</option>';
                                                echo '<option value="HU">Hungary</option>';
                                                echo '<option value="IS">Iceland</option>';
                                                echo '<option value="IN">India</option>';
                                                echo '<option value="ID">Indonesia</option>';
                                                echo '<option value="IQ">Iraq</option>';
                                                echo '<option value="IE">Ireland</option>';
                                                echo '<option value="IR">Islamic Republic of Iran</option>';
                                                echo '<option value="IM">Isle of Man</option>';
                                                echo '<option value="IL">Israel</option>';
                                                echo '<option value="IT">Italy</option>';
                                                echo '<option value="JM">Jamaica</option>';
                                                echo '<option value="JP">Japan</option>';
                                                echo '<option value="JO">Jordan</option>';
                                                echo '<option value="KZ">Kazakhstan</option>';
                                                echo '<option value="KE">Kenya</option>';
                                                echo '<option value="KI">Kiribati</option>';
                                                echo '<option value="KW">Kuwait</option>';
                                                echo '<option value="KG">Kyrgyzstan</option>';
                                                echo '<option value="LA">Lao People"s Democratic Republic</option>';
                                                echo '<option value="LV">Latvia</option>';
                                                echo '<option value="LB">Lebanon</option>';
                                                echo '<option value="LS">Lesotho</option>';
                                                echo '<option value="LR">Liberia</option>';
                                                echo '<option value="LY">Libyan Arab Jamahiriya</option>';
                                                echo '<option value="LI">Liechtenstein</option>';
                                                echo '<option value="LT">Lithuania</option>';
                                                echo '<option value="LU">Luxembourg</option>';
                                                echo '<option value="MO">Macao</option>';
                                                echo '<option value="MG">Madagascar</option>';
                                                echo '<option value="MW">Malawi</option>';
                                                echo '<option value="MY">Malaysia</option>';
                                                echo '<option value="MV">Maldives</option>';
                                                echo '<option value="ML">Mali</option>';
                                                echo '<option value="MT">Malta</option>';
                                                echo '<option value="MH">Marshall Islands</option>';
                                                echo '<option value="MQ">Martinique</option>';
                                                echo '<option value="MR">Mauritania</option>';
                                                echo '<option value="MU">Mauritius</option>';
                                                echo '<option value="YT">Mayotte</option>';
                                                echo '<option value="MX">Mexico</option>';
                                                echo '<option value="MC">Monaco</option>';
                                                echo '<option value="MN">Mongolia</option>';
                                                echo '<option value="MS">Montserrat</option>';
                                                echo '<option value="MA">Morocco</option>';
                                                echo '<option value="MZ">Mozambique</option>';
                                                echo '<option value="MM">Myanmar</option>';
                                                echo '<option value="NA">Namibia</option>';
                                                echo '<option value="NR">Nauru</option>';
                                                echo '<option value="NP">Nepal</option>';
                                                echo '<option value="NL">Netherlands</option>';
                                                echo '<option value="AN">Netherlands Antilles</option>';
                                                echo '<option value="NC">New Caledonia</option>';
                                                echo '<option value="NZ">New Zealand</option>';
                                                echo '<option value="NI">Nicaragua</option>';
                                                echo '<option value="NE">Niger</option>';
                                                echo '<option value="NG">Nigeria</option>';
                                                echo '<option value="NU">Niue</option>';
                                                echo '<option value="NF">Norfolk Island</option>';
                                                echo '<option value="MP">Northern Mariana Islands</option>';
                                                echo '<option value="NO">Norway</option>';
                                                echo '<option value="PS">Occupied Palestinian Territory</option>';
                                                echo '<option value="OM">Oman</option>';
                                                echo '<option value="PK">Pakistan</option>';
                                                echo '<option value="PW">Palau</option>';
                                                echo '<option value="PA">Panama</option>';
                                                echo '<option value="PG">Papua New Guinea</option>';
                                                echo '<option value="PY">Paraguay</option>';
                                                echo '<option value="PE">Peru</option>';
                                                echo '<option value="PH">Philippines</option>';
                                                echo '<option value="PN">Pitcairn</option>';
                                                echo '<option value="PL">Poland</option>';
                                                echo '<option value="PT">Portugal</option>';
                                                echo '<option value="PR">Puerto Rico</option>';
                                                echo '<option value="QA">Qatar</option>';
                                                echo '<option value="KR">Republic of Korea</option>';
                                                echo '<option value="MD">Republic of Moldova</option>';
                                                echo '<option value="CG">Republic of the Congo</option>';
                                                echo '<option value="RE">Réunion</option>';
                                                echo '<option value="RO">Romania</option>';
                                                echo '<option value="RU">Russian Federation</option>';
                                                echo '<option value="RW">Rwanda</option>';
                                                echo '<option value="SH">Saint Helena</option>';
                                                echo '<option value="KN">Saint Kitts and Nevis</option>';
                                                echo '<option value="LC">Saint Lucia</option>';
                                                echo '<option value="VC">Saint Vincent and the Grenadines</option>';
                                                echo '<option value="PM">Saint-Pierre and Miquelon</option>';
                                                echo '<option value="WS">Samoa</option>';
                                                echo '<option value="SM">San Marino</option>';
                                                echo '<option value="ST">Sao Tome and Principe</option>';
                                                echo '<option value="SA">Saudi Arabia</option>';
                                                echo '<option value="SN">Senegal</option>';
                                                echo '<option value="CS">Serbia and Montenegro</option>';
                                                echo '<option value="SC">Seychelles</option>';
                                                echo '<option value="SL">Sierra Leone</option>';
                                                echo '<option value="SG">Singapore</option>';
                                                echo '<option value="SK">Slovakia</option>';
                                                echo '<option value="SI">Slovenia</option>';
                                                echo '<option value="SB">Solomon Islands</option>';
                                                echo '<option value="SO">Somalia</option>';
                                                echo '<option value="ZA">South Africa</option>';
                                                echo '<option value="GS">South Georgia and the South Sandwich Islands</option>';
                                                echo '<option value="SS">South Sudan</option>';
                                                echo '<option value="ES">Spain</option>';
                                                echo '<option value="LK">Sri Lanka</option>';
                                                echo '<option value="SD">Sudan</option>';
                                                echo '<option value="SR">Suriname</option>';
                                                echo '<option value="SJ">Svalbard and Jan Mayen</option>';
                                                echo '<option value="SZ">Swaziland</option>';
                                                echo '<option value="SE">Sweden</option>';
                                                echo '<option value="CH">Switzerland</option>';
                                                echo '<option value="SY">Syrian Arab Republic</option>';
                                                echo '<option value="TW">Taiwan</option>';
                                                echo '<option value="TJ">Tajikistan</option>';
                                                echo '<option value="TH">Thailand</option>';
                                                echo '<option value="CD">The Democratic Republic Of The Congo</option>';
                                                echo '<option value="MK">The Former Yugoslav Republic of Macedonia</option>';
                                                echo '<option value="TL">Timor-Leste</option>';
                                                echo '<option value="TG">Togo</option>';
                                                echo '<option value="TK">Tokelau</option>';
                                                echo '<option value="TO">Tonga</option>';
                                                echo '<option value="TT">Trinidad and Tobago</option>';
                                                echo '<option value="TN">Tunisia</option>';
                                                echo '<option value="TR">Turkey</option>';
                                                echo '<option value="TM">Turkmenistan</option>';
                                                echo '<option value="TC">Turks and Caicos Islands</option>';
                                                echo '<option value="TV">Tuvalu</option>';
                                                echo '<option value="VI">U.S. Virgin Islands</option>';
                                                echo '<option value="UG">Uganda</option>';
                                                echo '<option value="UA">Ukraine</option>';
                                                echo '<option value="AE">United Arab Emirates</option>';
                                                echo '<option value="GB">United Kingdom</option>';
                                                echo '<option value="TZ">United Republic Of Tanzania</option>';
                                                echo '<option value="US">United States</option>';
                                                echo '<option value="UM">United States Minor Outlying Islands</option>';
                                                echo '<option value="UY">Uruguay</option>';
                                                echo '<option value="UZ">Uzbekistan</option>';
                                                echo '<option value="VU">Vanuatu</option>';
                                                echo '<option value="VA">Vatican City State</option>';
                                                echo '<option value="VE">Venezuela</option>';
                                                echo '<option value="VN">Vietnam</option>';
                                                echo '<option value="WF">Wallis and Futuna</option>';
                                                echo '<option value="EH">Western Sahara</option>';
                                                echo '<option value="YE">Yemen</option>';
                                                echo '<option value="ZM">Zambia</option>';
                                                echo '<option value="ZW">Zimbabwe</option>';
											echo '</select>';
	echo '<br>';											

		echo 'KEITARO: ';
		$landings = $keitaro->landingPages();
	
		echo '<select name="landing[1]">';
		echo '<option value="">Преленд</option>';
		foreach($landings as $item){
			echo '<option value="'.$item["id"].'">'.$item["name"].'</option>';
		}
		echo '</select>';

		echo '<select name="landing[2]">';
		echo '<option value="">Лендинг</option>';
		foreach($landings as $item){
			echo '<option value="'.$item["id"].'">'.$item["name"].'</option>';
		}
		echo '</select>';
		echo '<input type="submit" value="Отправить">';
	echo '</form>';

?>
